import 'server-only'

import { listEvents } from '@/lib/protocol/client'
import type { EventListItem } from '@/lib/protocol/types'

import { periodLabel, periodToDays } from './types'
import type { AiContextOptions } from './types'

/**
 * Generera strukturerad text-profil som användaren kan klistra in i
 * vilken som helst AI (ChatGPT, Claude, Gemini, lokal LLM). Bygger
 * ovanpå Selvra-protokollets events utan SREF-overhead — optimerat för
 * att vara LLM-friendly: tydlig struktur, kompakt, self-explanatory.
 *
 * Per Carl-prio 2026-05-11: agency-as-practice. Användaren tar sin egen
 * Selvra-context och delar med vilken AI som helst, utan att vara
 * inlåst i en specifik leverantörs minne.
 */

const INTRO = `You are talking to a user who maintains a structured representation of themselves via Selvra (https://selvra.ai). The text below is their current context, generated by Selvra and shared by them explicitly. Use it to understand who they are; do not moralize their data, do not give prescriptive advice unless they ask for it.`

const USAGE_GUIDANCE = `USAGE GUIDANCE:
- Reference specific items by their dates or types when discussing them.
- This is structured representation, not the full person. Treat as one input among others.
- Selvra observes patterns (the "BACKGROUND" section) — these are observations, not diagnoses.
- The user owns this representation. They generated this context and shared it intentionally.`

export async function generateAiContext(opts: AiContextOptions): Promise<string> {
  const cutoffDays = periodToDays(opts.period)
  const since = cutoffDays
    ? new Date(Date.now() - cutoffDays * 24 * 60 * 60 * 1000)
    : undefined

  const sections: string[] = []
  sections.push(INTRO)
  sections.push('')
  sections.push(`GENERATED: ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`)
  sections.push(`PERIOD: ${periodLabel(opts.period)}`)
  sections.push('')

  if (opts.layers.includes('intentions')) {
    sections.push(...(await renderIntentions(since)))
    sections.push('')
  }
  if (opts.layers.includes('thoughts')) {
    sections.push(...(await renderThoughts(since)))
    sections.push('')
  }
  if (opts.layers.includes('patterns')) {
    sections.push(...(await renderPatterns(since)))
    sections.push('')
  }

  sections.push(USAGE_GUIDANCE)
  return sections.join('\n')
}

async function renderIntentions(since: Date | undefined): Promise<string[]> {
  const res = await safeListEvents({
    eventType: 'selvra.intention.declared',
    since,
    limit: 100,
  })
  const out: string[] = []
  out.push('INTENTIONS (what the user says they want):')
  if (res.length === 0) {
    out.push('  (none declared in this period)')
    return out
  }

  // Filter ut delivery_rhythm-events; visa bara self_directed
  const selfDirected = res.filter(
    (e) => (e.payload as { intent_type?: string }).intent_type === 'self_directed',
  )
  const rhythms = res.filter(
    (e) => (e.payload as { intent_type?: string }).intent_type === 'delivery_rhythm',
  )

  if (selfDirected.length > 0) {
    // Reverse → oldest first (kronologiskt)
    for (const e of [...selfDirected].reverse()) {
      const p = e.payload as { text?: string }
      const date = e.created_at.slice(0, 10)
      out.push(`  - "${p.text ?? ''}" [declared ${date}]`)
    }
  } else {
    out.push('  (no self-directed intentions)')
  }

  if (rhythms.length > 0) {
    const latest = rhythms[0]
    const rhythm = (latest.payload as { value?: { rhythm?: string } }).value?.rhythm
    if (rhythm) {
      out.push('')
      out.push(`REFLECTION RHYTHM: ${rhythm} (when the user wants Selvra to reflect)`)
    }
  }
  return out
}

async function renderThoughts(since: Date | undefined): Promise<string[]> {
  const res = await safeListEvents({
    eventType: 'selvra.thought.recorded',
    since,
    limit: 200,
  })
  const out: string[] = []
  out.push('THOUGHTS (recent self-reports, oldest first):')
  if (res.length === 0) {
    out.push('  (none in this period)')
    return out
  }
  for (const e of [...res].reverse()) {
    const ts = e.created_at.slice(0, 16).replace('T', ' ')
    const text = (e.payload as { text?: string }).text ?? ''
    out.push(`  [${ts}] "${text}"`)
  }
  return out
}

async function renderPatterns(since: Date | undefined): Promise<string[]> {
  const res = await safeListEvents({
    eventType: 'insight.derived',
    since,
    limit: 100,
  })
  const out: string[] = []
  out.push('BACKGROUND OBSERVATIONS (patterns Selvra has detected autonomously):')
  if (res.length === 0) {
    out.push('  (none in this period)')
    return out
  }
  for (const e of res) {
    const p = e.payload as { key?: string; value?: { description?: string } }
    const key = p.key ?? '(unnamed)'
    const desc = p.value?.description ?? '(no description)'
    out.push(`  - ${key}: ${desc}`)
  }
  return out
}

async function safeListEvents(opts: {
  eventType: string
  since?: Date
  limit?: number
}): Promise<EventListItem[]> {
  try {
    const res = await listEvents(opts)
    return res.items
  } catch {
    return []
  }
}
